version: '3.8'

services:
  task-service:
    container_name: task-service
    image: t0ky0le/task-service:1.0
    build:
      context: .
    ports:
      - "8093:8093"
    environment:
      - SERVER_PORT=8093
      - DB_HOST=db_task
      - DB_PORT=3306
      - DB_NAME=db_task
      - DB_USERNAME=root
      - DB_PASSWORD=123
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_GROUP_ID=task-service-group
    depends_on:
      - db_task
      - kafka

  db_task:
    container_name: db_task
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_task
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "8104:3306"
    expose:
      - 3306
